### ISSUE TITLE
Missing Microcode Files

### ISSUE THREAD

**Issue by SkewedZeppelin** [intel/Intel-Linux-Processor-Microcode-Data-Files#10] opened 2019-06-24 21:20 UTC
This repository seems to be missing a large number of microcode files when compared to other 3rd party collections. As this is the repository most Linux distributions ship it should include all possible updates.

Please consider including the latest publically available production microcode files for the following:
```
06-01-01
06-01-02
06-01-06
06-01-07
06-01-09
06-03-00
06-03-03
06-03-04
06-07-00
06-08-00
06-09-00
06-09-01
06-09-02
06-09-04
06-09-06
06-0a-04
06-0b-00
06-0d-00
06-0d-01
06-0d-02
06-0d-08
06-0e-00
06-0e-01
06-0e-04
06-0f-00
06-0f-01
06-0f-04
06-0f-05
06-0f-09
06-15-00
06-16-00
06-17-00
06-17-01
06-17-04
06-1c-01
06-1c-09
06-1d-00
06-1e-04
06-2a-00
06-2a-01
06-2a-02
06-2a-03
06-2a-04
06-2a-05
06-2a-06
06-2c-01
06-2d-05
06-2f-00
06-2f-01
06-35-00
06-35-01
06-36-00
06-36-01
06-36-09
06-37-01
06-37-02
06-37-03
06-3a-00
06-3a-02
06-3a-04
06-3a-05
06-3a-06
06-3a-08
06-3e-00
06-3e-02
06-3e-03
06-3f-01
06-3f-03
06-4a-08
06-4a-09
06-4c-01
06-4c-02
06-4d-00
06-4d-08
06-4e-01
06-4e-02
06-4e-08
06-4f-00
06-55-03
06-55-05
06-55-06
06-57-01
06-5a-00
06-5c-08
06-5d-01
06-5e-00
06-5e-01
06-5e-02
06-5e-08
06-5f-00
06-66-00
06-66-01
06-66-02
06-66-03
06-7a-00
06-7e-00
06-7e-01
06-7e-02
06-7e-04
06-7e-05
06-85-00
0f-00-05
0f-00-06
0f-00-08
0f-00-09
0f-01-01
0f-01-03
0f-02-00
0f-02-01
0f-02-02
0f-02-03
0f-03-00
0f-03-01
0f-03-06
0f-03-07
0f-04-00
0f-04-02
0f-04-06
0f-06-00
0f-06-01
0f-06-03
0f-06-06
```

Also of note, some microcode files that are included do not seem to be the latest available.
For example 06-17-0a (penryn) included seems to be version 0a0a, when 0a0e was made available in 2015.

Inclusion of all available microcode files would be greatly appreciated by the Linux community.

**Comment by teoberi** [comment] 2019-06-25 05:46
For 06-17-0a (Q9550 - Yorkfield - cpuid 0x1067a) I have the microcode 0xa0b and the latest version is 0xa0e dated 2015/07/29 according to builtin MCExtractor DB v112 - 2019/05/22.

**Comment by teoberi** [comment] 2019-06-26 08:15
`For example 06-17-0a (penryn) included seems to be version 0a0a, when 0a0e was made available in 2015.`
cpuid1067a
https://github.com/platomav/CPUMicrocodes/tree/master/Intel

**Comment by hmh** [comment] 2019-07-02 11:49
Speaking as a distro maintainer:

- microcode updates for the SoCs *would be very welcome*.

  Some device vendors do release general-computing computers based on those, and they are just as good at distributing newer versions of their firmware as expected (i.e. they rarely do).  I have seen at least one report of one such SoC that crashes under Linux unless a (not-generally-available) microcode update is applied.

- We do NOT want microcode updates for any ES/QS processor steppings (there are many  ES/QS steppings in that list on the first post).  They're a waste of mirror space and network bandwidth.

  Those are of interest only to researchers. Linux distros don't even want to hear from *users* of such processors, as they seldom report truly weird bugs that end up being unreproducible (issues caused by errata long fixed on production steppings or production microcode updates), thus wasting very limited support resources.

- Reinstating the microcode updates for ancient, long-time EOL'd processors would be useful.

  However, those are mostly i686-class processors, which few Linux distros still support.  And at least Debian and Ubuntu already have a curated list of such microcode that any distro could use if they cared to.

**Comment by teoberi** [comment] 2019-07-02 13:43
> And at least Debian and Ubuntu already have a curated list of such microcode that any distro could use if they cared to.
Yes, Debian is a great source for such microcode but also for other patches (example p7zip).

**Closed** 2021-06-08 18:21 UTC
